// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1Sa9wabdE4TtIwuxnJ32UC96n6s0nhE',
    appId: '1:328861435208:web:ba2c8b61dbb55ad6459f7d',
    messagingSenderId: '328861435208',
    projectId: 'task-management-df2a6',
    authDomain: 'task-management-df2a6.firebaseapp.com',
    storageBucket: 'task-management-df2a6.appspot.com',
    measurementId: 'G-GWJBVPB2W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPvgCHvX5qPlARThgqVEpPn5BFaI6rI70',
    appId: '1:328861435208:android:f85a78884987694c459f7d',
    messagingSenderId: '328861435208',
    projectId: 'task-management-df2a6',
    storageBucket: 'task-management-df2a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7P64tihVPx-ieJMZP3cbLW8XzDpunwRQ',
    appId: '1:328861435208:ios:2fba488e91c983ad459f7d',
    messagingSenderId: '328861435208',
    projectId: 'task-management-df2a6',
    storageBucket: 'task-management-df2a6.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7P64tihVPx-ieJMZP3cbLW8XzDpunwRQ',
    appId: '1:328861435208:ios:2fba488e91c983ad459f7d',
    messagingSenderId: '328861435208',
    projectId: 'task-management-df2a6',
    storageBucket: 'task-management-df2a6.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA1Sa9wabdE4TtIwuxnJ32UC96n6s0nhE',
    appId: '1:328861435208:web:39cf2e75165e6498459f7d',
    messagingSenderId: '328861435208',
    projectId: 'task-management-df2a6',
    authDomain: 'task-management-df2a6.firebaseapp.com',
    storageBucket: 'task-management-df2a6.appspot.com',
    measurementId: 'G-CSBEXJZZEL',
  );
}
